load("//:py.bzl", "perplexity_py_library", "pytest_test")

perplexity_py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
)

pytest_test(
    name = "test_sessions_test",
    srcs = ["test_sessions.py"],
    deps = [
        "//src:perplexity",
        "//tests:conftest",
        "//tests:utils",
    ],
)
