# This workflow is triggered when a GitHub release is created.
# It can also be run manually to re-publish to PyPI in case it failed for some reason.
# You can run this workflow by navigating to https://www.github.com/perplexityai/perplexity-py/actions/workflows/publish-pypi.yml
name: Publish PyPI
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86
        with:
          bazelisk-cache: true
          repository-cache: true

      - name: Publish to PyPI
        run: bazel run //:wheel.publish -- --non-interactive
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PERPLEXITY_PYPI_TOKEN || secrets.PYPI_TOKEN }}
